REVOKE ALL ON schema public FROM public;
CREATE DATABASE testdb;

REVOKE CREATE ON schema public FROM public;
CREATE ROLE s1 WITH LOGIN PASSWORD 'students@mysql@DB3';
GRANT CONNECT ON DATABASE testdb TO s1;
GRANT USAGE ON SCHEMA public TO s1;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO s1;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO s1;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO s1;

CREATE ROLE teacher WITH LOGIN PASSWORD 'Oj4dblcui_';
GRANT ALL PRIVILEGES ON DATABASE testdb to teacher;
GRANT ALL ON schema public TO teacher;
ALTER USER teacher CREATEDB;
ALTER USER teacher SYSADMIN;
